
# <center> Practica</center>  
## <center> NOMBRE: Gemberth Josue Delgado Delgado</center> 
## <center>CURSO: 6to "B"</center> 
## <center>ASIGNATURA: MODELAMIENTO Y SIMULACIÓN</center> 
## <center>DOCENTE: JORGE ANIBAL MOYA DELGADO</center>

In [1]:
import pandas as pd
import numpy as np
datos = pd.read_csv('data.csv') 
#datos.head() 
datos

   PAGO   PROBABILIDAD
0      0          0.83
1    500          0.06
2   1000          0.05
3   2000          0.02
4   5000          0.02
5   8000          0.01
6  10000          0.01

In [2]:
#Calculamos las probabilidades de la Columna NO_ATENDIDOS
# Ordenamos por Día 
suma = datos['PROBABILIDAD'].sum() 
n=len(datos) 
suma 
x1 = datos.assign(Probabilidad=lambda x: x['PROBABILIDAD'] / suma) 

x2 = x1
a=x2['PROBABILIDAD'] 

a

0    0.83
1    0.06
2    0.05
3    0.02
4    0.02
5    0.01
6    0.01
Name: PROBABILIDAD, dtype: float64

In [3]:
a1= np.cumsum(a)      #Cálculo la suma acumulativa de las probabilidades 
x2['FPA'] =a1 
x2

   PAGO   PROBABILIDAD  Probabilidad   FPA
0      0          0.83          0.83  0.83
1    500          0.06          0.06  0.89
2   1000          0.05          0.05  0.94
3   2000          0.02          0.02  0.96
4   5000          0.02          0.02  0.98
5   8000          0.01          0.01  0.99
6  10000          0.01          0.01  1.00

In [4]:
x2['Min'] = x2['FPA']
x2['Max'] = x2['FPA']+0.001 
x2

   PAGO   PROBABILIDAD  Probabilidad   FPA   Min    Max
0      0          0.83          0.83  0.83  0.83  0.831
1    500          0.06          0.06  0.89  0.89  0.891
2   1000          0.05          0.05  0.94  0.94  0.941
3   2000          0.02          0.02  0.96  0.96  0.961
4   5000          0.02          0.02  0.98  0.98  0.981
5   8000          0.01          0.01  0.99  0.99  0.991
6  10000          0.01          0.01  1.00  1.00  1.001

In [5]:
lis = x2["Min"].values 
lis2 = x2['Max'].values 
lis[0]= 0 
for i in range(1,len(lis)):    
    lis[i] = lis2[i-1]    
    print(i,i-1) 
x2['Min'] = lis
x2

1 0
2 1
3 2
4 3
5 4
6 5

   PAGO   PROBABILIDAD  Probabilidad   FPA    Min    Max
0      0          0.83          0.83  0.83  0.000  0.831
1    500          0.06          0.06  0.89  0.831  0.891
2   1000          0.05          0.05  0.94  0.891  0.941
3   2000          0.02          0.02  0.96  0.941  0.961
4   5000          0.02          0.02  0.98  0.961  0.981
5   8000          0.01          0.01  0.99  0.981  0.991
6  10000          0.01          0.01  1.00  0.991  1.001

In [6]:
n, m, a, x0, c = 60, 2**32, 22695477, 4, 1
x = [1] * n
r = [0.1] * n
for i in range(0, n):
    x[i] = ((a*x0)+c) % m
    x0 = x[i]
    r[i] = x0 / m
# llenamos nuestro DataFrame
d = {'ri': r }
dfMCL = pd.DataFrame(data=d)
dfMCL

          ri
0   0.021137
1   0.992121
2   0.164339
3   0.063835
4   0.661529
5   0.400824
6   0.248127
7   0.586098
8   0.107008
9   0.849288
10  0.624741
11  0.476402
12  0.051529
13  0.232983
14  0.081332
15  0.736542
16  0.268061
17  0.883159
18  0.647850
19  0.000471
20  0.508672
21  0.177622
22  0.999577
23  0.524479
24  0.764966
25  0.750150
26  0.087186
27  0.736931
28  0.685749
29  0.532911
30  0.416229
31  0.706958
32  0.198789
33  0.116261
34  0.647896
35  0.141468
36  0.633563
37  0.160312
38  0.442957
39  0.769847
40  0.891846
41  0.842619
42  0.720730
43  0.225738
44  0.463035
45  0.576381
46  0.754969
47  0.785257
48  0.331067
49  0.483528
50  0.778536
51  0.571038
52  0.069817
53  0.357058
54  0.018744
55  0.081464
56  0.673851
57  0.097015
58  0.335234
59  0.154478

In [7]:
max = x2 ['Max'].values
min = x2 ['Min'].values

In [8]:
print(min)
print(max)

[0.    0.831 0.891 0.941 0.961 0.981 0.991]
[0.831 0.891 0.941 0.961 0.981 0.991 1.001]

In [9]:
def busqueda(arrmin, arrmax, valor):
    #print(valor)
    for i in range (len(arrmin)):
        # print(arrmin[i],arrmax[i])
        if valor >= arrmin[i] and valor <= arrmax[i]:
            return i
            print(i)
    return -1
xpos = dfMCL['ri']
posi = [0] * n
print (n)
for j in range(n):
    val = xpos[j]
    pos = busqueda(min,max,val)
    posi[j] = pos

60

In [10]:
x2 = x2.astype({"PROBABILIDAD" : int})
x2

   PAGO   PROBABILIDAD  Probabilidad   FPA    Min    Max
0      0             0          0.83  0.83  0.000  0.831
1    500             0          0.06  0.89  0.831  0.891
2   1000             0          0.05  0.94  0.891  0.941
3   2000             0          0.02  0.96  0.941  0.961
4   5000             0          0.02  0.98  0.961  0.981
5   8000             0          0.01  0.99  0.981  0.991
6  10000             0          0.01  1.00  0.991  1.001

In [11]:
x2.dtypes

PAGO              int64
PROBABILIDAD      int32
Probabilidad    float64
FPA             float64
Min             float64
Max             float64
dtype: object

In [12]:
x2.axes[0]

RangeIndex(start=0, stop=7, step=1)

In [17]:
x2.set_index('PROBABILIDAD')

              PAGO   Probabilidad   FPA    Min    Max
PROBABILIDAD
0                 0          0.83  0.83  0.000  0.831
0               500          0.06  0.89  0.831  0.891
0              1000          0.05  0.94  0.891  0.941
0              2000          0.02  0.96  0.941  0.961
0              5000          0.02  0.98  0.961  0.981
0              8000          0.01  0.99  0.981  0.991
0             10000          0.01  1.00  0.991  1.001

In [21]:
import itertools
import math
simula = []
for j in range(n):
    for i in range(n):
        sim = x2.loc[x2["Probabilidad"] == posi[i]+1]
        simu = sim.filter(['Probabilidad']).values
        iterator = itertools.chain(*simu)
        for item in iterator:
            a=item
        simula.append(round(a,2))
simula

[22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 22695477,
 ...]

In [22]:
dfMCL["Simulación"] = pd.DataFrame(simula)
dfMCL["Costo de Atención"] = dfMCL["Simulación"] * 60

In [23]:
dfMCL

          ri  Simulación  Costo de Atención
0   0.021137    22695477         1361728620
1   0.992121    22695477         1361728620
2   0.164339    22695477         1361728620
3   0.063835    22695477         1361728620
4   0.661529    22695477         1361728620
5   0.400824    22695477         1361728620
6   0.248127    22695477         1361728620
7   0.586098    22695477         1361728620
8   0.107008    22695477         1361728620
9   0.849288    22695477         1361728620
10  0.624741    22695477         1361728620
11  0.476402    22695477         1361728620
12  0.051529    22695477         1361728620
13  0.232983    22695477         1361728620
14  0.081332    22695477         1361728620
15  0.736542    22695477         1361728620
16  0.268061    22695477         1361728620
17  0.883159    22695477         1361728620
18  0.647850    22695477         1361728620
19  0.000471    22695477         1361728620
20  0.508672    22695477         1361728620
21  0.177622    22695477         1361728620
22  0.999577    22695477         1361728620
23  0.524479    22695477         1361728620
24  0.764966    22695477         1361728620
25  0.750150    22695477         1361728620
26  0.087186    22695477         1361728620
27  0.736931    22695477         1361728620
28  0.685749    22695477         1361728620
29  0.532911    22695477         1361728620
30  0.416229    22695477         1361728620
31  0.706958    22695477         1361728620
32  0.198789    22695477         1361728620
33  0.116261    22695477         1361728620
34  0.647896    22695477         1361728620
35  0.141468    22695477         1361728620
36  0.633563    22695477         1361728620
37  0.160312    22695477         1361728620
38  0.442957    22695477         1361728620
39  0.769847    22695477         1361728620
40  0.891846    22695477         1361728620
41  0.842619    22695477         1361728620
42  0.720730    22695477         1361728620
43  0.225738    22695477         1361728620
44  0.463035    22695477         1361728620
45  0.576381    22695477         1361728620
46  0.754969    22695477         1361728620
47  0.785257    22695477         1361728620
48  0.331067    22695477         1361728620
49  0.483528    22695477         1361728620
50  0.778536    22695477         1361728620
51  0.571038    22695477         1361728620
52  0.069817    22695477         1361728620
53  0.357058    22695477         1361728620
54  0.018744    22695477         1361728620
55  0.081464    22695477         1361728620
56  0.673851    22695477         1361728620
57  0.097015    22695477         1361728620
58  0.335234    22695477         1361728620
59  0.154478    22695477         1361728620